### PR TITLE
Made a python text to speech script with Readme and other requirements.

### LINKED ISSUE #9: Text to Speech converter.
The user should input text your task is to convert it to audio.
Make a separate folder for this.

### PR DESCRIPTION
**Pull request by anima-regem**
fixes #9

### CODE REVIEW

**Comment by Divyansh1011** [comment]
We cant hear the speech...that is your text getting converted to speech...try reshooting the video so that its a bit audible..otherwise great job..we will review your  PR once you update the README file with the updated video

**Comment by anima-regem** [comment]
Thanks, and sorry, It's my first time doing this.

**Comment by Divyansh1011** [comment]
@anima-regem  Great job thats the aim we wanna help first timers makeing there first request!!! and you have just entered the world of open source... now drop your discord id here 
if you havent joined our server here is the link: https://discord.gg/spZnGB3Rkh

**Comment by anima-regem** [comment]
d81e8213797f23651cf57e59b4bd8da0#7400

discord id

**Pull request closed without merging**
